name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  frontend-build-test:
    name: Frontend Lint, Build & Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./task-manager-frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'task-manager-frontend/package-lock.json'
      - run: npm install
      - run: npm run lint
      - run: npm run build
      - run: npx vitest run --coverage src

  frontend-e2e:
    name: Frontend Pruebas E2E
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./task-manager-frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'task-manager-frontend/package-lock.json'
      - run: npm install
      - run: npx playwright install --with-deps chromium
      - run: npx playwright test

  backend-build:
    name: Backend Lint & Typecheck
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./task-manager-backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'task-manager-backend/package-lock.json'
      - run: npm install
      - run: npx prisma generate
      - run: npx tsc --noEmit